# meetbot service
---
apiVersion: v1
kind: Service
metadata:
  name: meetbot-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    name: meet-log-http
    targetPort: 8080
    protocol: TCP  
  - port: 81
    name: meet-bot-http
    targetPort: 80
    protocol: TCP
  selector:
    app: meet-bot
  type: LoadBalancer
